# permissions for end users to view betaresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: betaresource-viewer-role
rules:
- apiGroups:
  - betactrl.betatest.io
  resources:
  - betaresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - betactrl.betatest.io
  resources:
  - betaresources/status
  verbs:
  - get
