
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - betactrl.betatest.io
  resources:
  - betaresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - betactrl.betatest.io
  resources:
  - betaresources/status
  verbs:
  - get
  - patch
  - update
